# Generated by Django 5.2.8 on 2025-11-20 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary login identifier",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("dean", "Dean"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                        ],
                        db_index=True,
                        help_text="User role determines access permissions",
                        max_length=20,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile-images/"
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("major", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivation_reason", models.TextField(blank=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_page_path", models.CharField(blank=True, max_length=500)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("last_user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used", models.BooleanField(db_index=True, default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Verification Tokens",
                "db_table": "email_verification_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hashed_password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Password History",
                "db_table": "password_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hashed token",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used", models.BooleanField(db_index=True, default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Password Reset Tokens",
                "db_table": "password_reset_tokens",
            },
        ),
        migrations.CreateModel(
            name="StudentInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("graduated", "Graduated"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current enrollment status",
                        max_length=20,
                    ),
                ),
                (
                    "enrollment_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique student ID/roll number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "enrolled_courses_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of active enrollments"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned class section (K-12 homeroom)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_infos",
                        to="academics.classsection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Info",
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="TeacherInfo",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="teacher_info",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Senior Teacher, Lead Teacher, Department Head, Dean",
                        max_length=255,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Mathematics, Physics, Computer Science",
                        max_length=255,
                    ),
                ),
                (
                    "courses_count",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Number of active course offerings",
                    ),
                ),
                (
                    "subjects_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of assigned subjects"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Teacher Info",
                "db_table": "teachers",
                "indexes": [
                    models.Index(
                        fields=["courses_count"], name="teachers_courses_66fd06_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="users_role_0ace22_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_active"], name="users_is_acti_847b48_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_role_a8f2ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["token"], name="email_verif_token_df7c5e_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(
                fields=["expires_at"], name="email_verif_expires_770728_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(
                fields=["user", "used"], name="email_verif_user_id_867e40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="password_hi_user_id_53e9ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["token"], name="password_re_token_060a1f_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["expires_at"], name="password_re_expires_8e96b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "used"], name="password_re_user_id_4cd856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "created_at"], name="password_re_user_id_aa22c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentinfo",
            index=models.Index(fields=["status"], name="students_status_3ac771_idx"),
        ),
        migrations.AddIndex(
            model_name="studentinfo",
            index=models.Index(
                fields=["enrollment_number"], name="students_enrollm_a0886f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentinfo",
            index=models.Index(
                fields=["class_section"], name="students_class_s_68391d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentinfo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "inactive", "graduated", "suspended"])
                ),
                name="valid_student_status",
            ),
        ),
    ]
