# Generated by Django 5.2.8 on 2025-11-20 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Rich text/HTML instructions"),
                ),
                ("due_date", models.DateTimeField(db_index=True)),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assignments/attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "ppt", "pptx", "jpg", "png"]
                            )
                        ],
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Assignment Attachment",
                "verbose_name_plural": "Assignment Attachments",
                "db_table": "assignment_attachments",
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Assignment Submission",
                "verbose_name_plural": "Assignment Submissions",
                "db_table": "assignment_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("hint", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
                "db_table": "flashcards",
                "ordering": ["module", "order"],
            },
        ),
        migrations.CreateModel(
            name="FlashcardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ease_factor",
                    models.FloatField(
                        default=2.5,
                        validators=[
                            django.core.validators.MinValueValidator(1.3),
                            django.core.validators.MaxValueValidator(2.5),
                        ],
                    ),
                ),
                ("interval_days", models.PositiveIntegerField(default=1)),
                ("repetitions", models.PositiveIntegerField(default=0)),
                (
                    "last_reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("correct_reviews", models.PositiveIntegerField(default=0)),
                ("is_mastered", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Flashcard Progress",
                "verbose_name_plural": "Flashcard Progress",
                "db_table": "flashcard_progress",
                "ordering": ["next_review_at"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_practice", models.BooleanField(default=False)),
                ("show_answers_after", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "db_table": "quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("total_points_earned", models.PositiveIntegerField(default=0)),
                ("total_points_possible", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("passed", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "Quiz Attempt",
                "verbose_name_plural": "Quiz Attempts",
                "db_table": "quiz_attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttemptAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("matching_answer", models.JSONField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("points_earned", models.PositiveIntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quiz Attempt Answer",
                "verbose_name_plural": "Quiz Attempt Answers",
                "db_table": "quiz_attempt_answers",
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("fill", "Fill in the Blank"),
                            ("tf", "True/False"),
                            ("match", "Matching"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField()),
                ("matching_pairs", models.JSONField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True)),
                ("points", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quiz Question",
                "verbose_name_plural": "Quiz Questions",
                "db_table": "quiz_questions",
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="assignments/submissions/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx", "jpg", "png", "zip"]
                            )
                        ],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Submission Attachment",
                "verbose_name_plural": "Submission Attachments",
                "db_table": "submission_attachments",
            },
        ),
        migrations.CreateModel(
            name="Worksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("topic", models.CharField(max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("grade_level", models.CharField(blank=True, max_length=50)),
                (
                    "worksheet_file",
                    models.FileField(
                        upload_to="worksheets/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "answer_key_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="worksheets/answers/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("is_ai_generated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Worksheet",
                "verbose_name_plural": "Worksheets",
                "db_table": "worksheets",
                "ordering": ["-created_at"],
            },
        ),
    ]
