# Generated by Django 5.2.8 on 2025-11-22 06:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSessionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of chat sessions"
                    ),
                ),
                (
                    "active_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of active sessions"
                    ),
                ),
                (
                    "completed_sessions",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completed sessions"
                    ),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(
                        default=0, help_text="Total messages across all sessions"
                    ),
                ),
                (
                    "total_time_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Total time spent chatting (seconds)"
                    ),
                ),
                (
                    "last_chat_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Chat Session Metrics",
                "db_table": "chat_session_metrics",
                "ordering": ["-last_chat_at"],
            },
        ),
        migrations.CreateModel(
            name="FlashcardSetProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cards",
                    models.PositiveIntegerField(
                        default=0, help_text="Total active flashcards in this module"
                    ),
                ),
                (
                    "mastered_cards",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of mastered cards (ease >= 2.5, interval >= 21)",
                    ),
                ),
                (
                    "mastery_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of cards mastered",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cards_due_today",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of cards due for review today"
                    ),
                ),
                (
                    "next_review_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Next scheduled review time",
                        null=True,
                    ),
                ),
                (
                    "is_fully_mastered",
                    models.BooleanField(
                        db_index=True, default=False, help_text="All cards are mastered"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Flashcard Set Progress",
                "db_table": "flashcard_set_progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPathProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("locked", "Locked"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("last_step_key", models.CharField(blank=True, max_length=255)),
                ("progress_index", models.PositiveIntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_unlocked", models.BooleanField(db_index=True, default=True)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Learning Path Progress",
                "verbose_name_plural": "Learning Path Progress",
                "db_table": "learning_path_progress",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "last_accessed_at",
                    models.DateTimeField(auto_now=True, db_index=True),
                ),
                ("progress_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lesson Progress",
                "verbose_name_plural": "Lesson Progress",
                "db_table": "lesson_progress",
                "ordering": ["-last_accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="PathRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz Minimum Score"),
                            ("assignment", "Assignment Minimum Grade"),
                            ("flashcard", "Flashcard Mastery %"),
                            ("chat", "Chat Minimum Messages"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "minimum_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum score % (for quiz/assignment)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "minimum_mastery",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum mastery % (for flashcards)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "minimum_messages",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum chat messages",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Weight for overall completion calculation",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Must complete to unlock next path",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Path Requirements",
                "db_table": "path_requirements",
                "ordering": ["path", "order"],
            },
        ),
        migrations.CreateModel(
            name="PathRequirementState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Progress towards requirement (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "current_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Current best score (if applicable)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of attempts"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_event_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Last time student worked on this requirement",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Path Requirement States",
                "db_table": "path_requirement_states",
                "ordering": ["requirement__order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttemptSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Best score achieved (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "last_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Most recent score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average score across all attempts",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of attempts"
                    ),
                ),
                (
                    "passed_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of attempts that passed"
                    ),
                ),
                (
                    "has_passed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Has student ever passed this quiz?",
                    ),
                ),
                (
                    "average_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Average time taken per attempt (seconds)",
                        null=True,
                    ),
                ),
                (
                    "question_progress",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-question correctness tracking",
                    ),
                ),
                ("first_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Quiz Attempt Summaries",
                "db_table": "quiz_attempt_summaries",
                "ordering": ["-last_attempt_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(
                        db_index=True,
                        help_text="Topic/category name (e.g., Grammar, Algebra)",
                        max_length=255,
                    ),
                ),
                (
                    "strength_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="AI-calculated strength score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "strength_level",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("developing", "Developing"),
                            ("proficient", "Proficient"),
                            ("strong", "Strong"),
                        ],
                        db_index=True,
                        default="developing",
                        max_length=20,
                    ),
                ),
                (
                    "ai_insights",
                    models.TextField(
                        blank=True, help_text="AI-generated insights about performance"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="AI-recommended actions/content",
                    ),
                ),
                (
                    "quiz_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average quiz score for this topic",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "assignment_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average assignment grade for this topic",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "flashcard_mastery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Flashcard mastery percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When this analysis was last updated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Topic Analytics",
                "db_table": "topic_analytics",
                "ordering": ["student", "strength_score"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Grade (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, help_text="Teacher feedback"),
                ),
                (
                    "is_late",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Was submission late?"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="assessments.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Assignment Progress",
                "db_table": "assignment_progress",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
