# Generated by Django 5.2.8 on 2025-11-22 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0002_initial"),
        ("courses", "0002_initial"),
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentprogress",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatsessionmetric",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_metrics",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="chatsessionmetric",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flashcardsetprogress",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_progress",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="flashcardsetprogress",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flashcard_set_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="learningpathprogress",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="courses.coursepath",
            ),
        ),
        migrations.AddField(
            model_name="learningpathprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pathrequirement",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="courses.coursepath",
            ),
        ),
        migrations.AddField(
            model_name="pathrequirement",
            name="target_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_requirements",
                to="assessments.assignment",
            ),
        ),
        migrations.AddField(
            model_name="pathrequirement",
            name="target_module",
            field=models.ForeignKey(
                blank=True,
                help_text="For flashcard/chat requirements",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_requirements",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="pathrequirement",
            name="target_quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_requirements",
                to="assessments.quiz",
            ),
        ),
        migrations.AddField(
            model_name="pathrequirementstate",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_states",
                to="progress.pathrequirement",
            ),
        ),
        migrations.AddField(
            model_name="pathrequirementstate",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirement_states",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quizattemptsummary",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_summaries",
                to="assessments.quiz",
            ),
        ),
        migrations.AddField(
            model_name="quizattemptsummary",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_summaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="topicanalytics",
            name="course",
            field=models.ForeignKey(
                help_text="Course this analytics belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_analytics",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="topicanalytics",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic_analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentprogress",
            index=models.Index(
                fields=["student", "status"], name="assignment__student_1e8218_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentprogress",
            index=models.Index(
                fields=["assignment", "status"], name="assignment__assignm_4524f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentprogress",
            index=models.Index(
                fields=["submitted_at"], name="assignment__submitt_d6668c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignmentprogress",
            index=models.Index(
                fields=["is_late"], name="assignment__is_late_788dc4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignmentprogress",
            unique_together={("student", "assignment")},
        ),
        migrations.AddIndex(
            model_name="chatsessionmetric",
            index=models.Index(
                fields=["student"], name="chat_sessio_student_56d30c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsessionmetric",
            index=models.Index(
                fields=["module"], name="chat_sessio_module__0e672b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsessionmetric",
            index=models.Index(
                fields=["last_chat_at"], name="chat_sessio_last_ch_d74352_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatsessionmetric",
            unique_together={("student", "module")},
        ),
        migrations.AddIndex(
            model_name="flashcardsetprogress",
            index=models.Index(
                fields=["student", "is_fully_mastered"],
                name="flashcard_s_student_fe5335_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flashcardsetprogress",
            index=models.Index(
                fields=["module"], name="flashcard_s_module__cde93c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flashcardsetprogress",
            index=models.Index(
                fields=["next_review_at"], name="flashcard_s_next_re_fced17_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flashcardsetprogress",
            unique_together={("student", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="learningpathprogress",
            unique_together={("student", "path")},
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["student", "is_completed"],
                name="lesson_prog_student_b7dc83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["module", "is_completed"], name="lesson_prog_module__ba9363_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("student", "module")},
        ),
        migrations.AddIndex(
            model_name="pathrequirement",
            index=models.Index(
                fields=["path", "is_mandatory"], name="path_requir_path_id_8f9ec0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathrequirement",
            index=models.Index(
                fields=["requirement_type"], name="path_requir_require_918eb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathrequirementstate",
            index=models.Index(
                fields=["student", "state"], name="path_requir_student_ea7560_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathrequirementstate",
            index=models.Index(
                fields=["requirement", "state"], name="path_requir_require_4daa2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathrequirementstate",
            index=models.Index(
                fields=["last_event_at"], name="path_requir_last_ev_066766_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pathrequirementstate",
            unique_together={("student", "requirement")},
        ),
        migrations.AddIndex(
            model_name="quizattemptsummary",
            index=models.Index(
                fields=["student", "has_passed"], name="quiz_attemp_student_833e21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizattemptsummary",
            index=models.Index(fields=["quiz"], name="quiz_attemp_quiz_id_25af51_idx"),
        ),
        migrations.AddIndex(
            model_name="quizattemptsummary",
            index=models.Index(
                fields=["last_attempt_at"], name="quiz_attemp_last_at_aed03e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizattemptsummary",
            unique_together={("student", "quiz")},
        ),
        migrations.AddIndex(
            model_name="topicanalytics",
            index=models.Index(
                fields=["student", "strength_level"],
                name="topic_analy_student_3a14c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topicanalytics",
            index=models.Index(
                fields=["course", "topic_name"], name="topic_analy_course__14c84e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topicanalytics",
            index=models.Index(
                fields=["strength_score"], name="topic_analy_strengt_1a4504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topicanalytics",
            index=models.Index(
                fields=["analyzed_at"], name="topic_analy_analyze_b4b4c5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topicanalytics",
            unique_together={("student", "course", "topic_name")},
        ),
    ]
