# Generated by Django 5.2.8 on 2025-11-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about absence/lateness"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance",
                "ordering": ["-class_session__session_date"],
            },
        ),
        migrations.CreateModel(
            name="ClassSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        db_index=True,
                        help_text="Section identifier (A, B, C, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Grade 5-A, Grade 10-B", max_length=255
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Maximum students in this section (typically 20-40)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Mark section as active/inactive",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class Section",
                "verbose_name_plural": "Class Sections",
                "db_table": "class_sections",
                "ordering": ["term", "section"],
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_date",
                    models.DateField(db_index=True, help_text="Date of class session"),
                ),
                ("start_time", models.TimeField(help_text="Class start time")),
                ("end_time", models.TimeField(help_text="Class end time")),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Topic covered in this session",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional session notes"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Mark session as cancelled",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, help_text="Reason for cancellation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Class Session",
                "verbose_name_plural": "Class Sessions",
                "db_table": "class_sessions",
                "ordering": ["-session_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Auto-generated URL slug", max_length=255, unique=True
                    ),
                ),
                (
                    "auto_enroll",
                    models.CharField(
                        choices=[
                            ("none", "Manual enrollment only"),
                            ("section", "Auto-enroll section students (K-12)"),
                        ],
                        default="section",
                        help_text="Automatic enrollment strategy for K-12",
                        max_length=10,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max students (overrides section capacity if set)",
                        null=True,
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("not_generated", "Not Generated"),
                            ("partial", "Partial"),
                            ("complete", "Complete"),
                        ],
                        db_index=True,
                        default="not_generated",
                        help_text="AI content generation status",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course Offering",
                "verbose_name_plural": "Course Offerings",
                "db_table": "course_offerings",
                "ordering": ["-term__start_date", "course__title"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dropped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student dropped the course",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When course was completed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "db_table": "enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentWaitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Position in waitlist (1 = first in line)",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Enrollment Waitlist",
                "verbose_name_plural": "Enrollment Waitlist",
                "db_table": "enrollment_waitlist",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="OfferingTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Primary teacher for grading/reporting",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Offering Teacher",
                "verbose_name_plural": "Offering Teachers",
                "db_table": "offering_teachers",
                "ordering": ["-is_primary", "assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("not_eligible", "Not Eligible"),
                            ("override", "Override (Eligible)"),
                            ("pending_review", "Pending Review"),
                        ],
                        db_index=True,
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why student is/isn't eligible"
                    ),
                ),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Eligibility",
                "verbose_name_plural": "Student Eligibilities",
                "db_table": "student_eligibilities",
                "ordering": ["status", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student Section Assignment",
                "verbose_name_plural": "Student Section Assignments",
                "db_table": "student_sections",
                "ordering": ["class_section__name", "student__name"],
            },
        ),
        migrations.CreateModel(
            name="StudentSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Mark assignment as active/inactive",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student Subject Assignment",
                "verbose_name_plural": "Student Subject Assignments",
                "db_table": "student_subjects",
                "ordering": ["term__number", "student__name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Teacher Subject Assignment",
                "verbose_name_plural": "Teacher Subject Assignments",
                "db_table": "teacher_subjects",
                "ordering": ["teacher__name", "subject__name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Mark assignment as active/inactive",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Teacher Grade Assignment",
                "verbose_name_plural": "Teacher Grade Assignments",
                "db_table": "teacher_terms",
                "ordering": ["term__number", "teacher__name"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(help_text="Grade number (1-12)"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Grade 5, Grade 10", max_length=255
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Grade start date (usually same as academic year start)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Grade end date (usually same as academic year end)"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Mark if this grade is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Term (Grade)",
                "verbose_name_plural": "Terms (Grades)",
                "db_table": "terms",
                "ordering": ["academic_year", "number"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Format: YYYY-YYYY (e.g., 2024-2025, must match start/end years)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Academic year start date (e.g., 2024-09-01)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Academic year end date (e.g., 2025-08-31)"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Mark one academic year as current (only one allowed)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "db_table": "academic_years",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_current"], name="academic_ye_is_curr_307122_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="academic_ye_start_d_95a9d0_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="academic_ye_end_dat_f101aa_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="unique_current_academic_year",
                    )
                ],
            },
        ),
    ]
