# Generated by Django 5.2.8 on 2025-11-22 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who marked the attendance",
                limit_choices_to={"role__in": ["teacher", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classsection",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Homeroom teacher for this section",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="class_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="academics.classsession",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="class_section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_offerings",
                to="academics.classsection",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offerings",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sessions",
                to="academics.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollmentwaitlist",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waitlist",
                to="academics.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentwaitlist",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_waitlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="offeringteacher",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="academics.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="offeringteacher",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taught_offerings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studenteligibility",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_eligibilities",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="studenteligibility",
            name="overridden_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin/Dean who overrode eligibility",
                limit_choices_to={"role__in": ["admin", "dean"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eligibility_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studenteligibility",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligibilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentsection",
            name="class_section",
            field=models.ForeignKey(
                help_text="Class section (homeroom)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="academics.classsection",
            ),
        ),
        migrations.AddField(
            model_name="studentsection",
            name="student",
            field=models.ForeignKey(
                help_text="Student assigned to this section",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="student",
            field=models.ForeignKey(
                help_text="Student enrolled in this subject",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject the student studies",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="courses.subject",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="subject",
            field=models.ForeignKey(
                help_text="Subject the teacher is qualified to teach",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="courses.subject",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher assigned to this subject",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teacherterm",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher assigned to this grade",
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="term_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="academic_year",
            field=models.ForeignKey(
                help_text="Academic year this grade belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terms",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="teacherterm",
            name="term",
            field=models.ForeignKey(
                help_text="Grade level (1-12)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="academics.term",
            ),
        ),
        migrations.AddField(
            model_name="studentsubject",
            name="term",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade level for this subject (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.term",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_offerings",
                to="academics.term",
            ),
        ),
        migrations.AddField(
            model_name="classsection",
            name="term",
            field=models.ForeignKey(
                help_text="Grade level (1-12)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_sections",
                to="academics.term",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "status"], name="attendance_student_bc7a65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["class_session", "status"], name="attendance_class_s_415540_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "class_session")},
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(
                fields=["offering", "session_date"],
                name="class_sessi_offerin_705eba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(
                fields=["is_cancelled"], name="class_sessi_is_canc_bd5d2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsession",
            index=models.Index(
                fields=["session_date"], name="class_sessi_session_7ba2aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["status"], name="enrollments_status_dfab18_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="enrollments_student_929bef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["offering", "status"], name="enrollments_offerin_eff35e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "offering")},
        ),
        migrations.AddIndex(
            model_name="enrollmentwaitlist",
            index=models.Index(
                fields=["offering", "position"], name="enrollment__offerin_ef2c35_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollmentwaitlist",
            unique_together={("student", "offering")},
        ),
        migrations.AddIndex(
            model_name="offeringteacher",
            index=models.Index(
                fields=["offering", "is_primary"], name="offering_te_offerin_870136_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offeringteacher",
            index=models.Index(
                fields=["teacher"], name="offering_te_teacher_1eb881_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="offeringteacher",
            unique_together={("offering", "teacher")},
        ),
        migrations.AddIndex(
            model_name="studenteligibility",
            index=models.Index(
                fields=["student", "status"], name="student_eli_student_f939e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studenteligibility",
            index=models.Index(
                fields=["course", "status"], name="student_eli_course__de6ec6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studenteligibility",
            unique_together={("student", "course")},
        ),
        migrations.AddIndex(
            model_name="studentsection",
            index=models.Index(
                fields=["class_section"], name="student_sec_class_s_46599c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsection",
            index=models.Index(
                fields=["student"], name="student_sec_student_641596_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentsection",
            unique_together={("student", "class_section")},
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["teacher"], name="teacher_sub_teacher_fc2ae6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubject",
            index=models.Index(
                fields=["subject"], name="teacher_sub_subject_8d2f5a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachersubject",
            unique_together={("teacher", "subject")},
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(fields=["is_current"], name="terms_is_curr_ed439a_idx"),
        ),
        migrations.AddIndex(
            model_name="term",
            index=models.Index(
                fields=["academic_year", "number"], name="terms_academi_5c99a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "number"),
                name="unique_grade_per_academic_year",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherterm",
            index=models.Index(
                fields=["teacher", "is_active"], name="teacher_ter_teacher_749977_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherterm",
            index=models.Index(
                fields=["term", "is_active"], name="teacher_ter_term_id_2ac3f2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teacherterm",
            unique_together={("teacher", "term")},
        ),
        migrations.AddIndex(
            model_name="studentsubject",
            index=models.Index(
                fields=["student", "is_active"], name="student_sub_student_ebe930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentsubject",
            index=models.Index(
                fields=["subject", "is_active"], name="student_sub_subject_a1699d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentsubject",
            unique_together={("student", "subject", "term")},
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["is_active"], name="course_offe_is_acti_f961d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["generation_status"], name="course_offe_generat_8953b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["course", "term"], name="course_offe_course__f23877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(fields=["slug"], name="course_offe_slug_3c3a83_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courseoffering",
            unique_together={("course", "term", "class_section")},
        ),
        migrations.AddIndex(
            model_name="classsection",
            index=models.Index(
                fields=["is_active"], name="class_secti_is_acti_d4cf6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classsection",
            index=models.Index(
                fields=["term", "section"], name="class_secti_term_id_43fab0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="classsection",
            constraint=models.UniqueConstraint(
                fields=("term", "section"), name="unique_k12_section"
            ),
        ),
    ]
