# Generated by Django 5.2.8 on 2025-11-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "outcomes",
                    models.TextField(blank=True, help_text="Course learning outcomes"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("SCHOOL", "School"), ("UNIV", "University")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("credit_hours", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "syllabus_file",
                    models.FileField(blank=True, null=True, upload_to="syllabus/"),
                ),
                (
                    "syllabus_analysis_status",
                    models.CharField(
                        choices=[
                            ("not_analyzed", "Not Analyzed"),
                            ("analyzing", "Analyzing"),
                            ("analyzed", "Analyzed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="not_analyzed",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ModuleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Rich Text"),
                            ("pdf", "PDF File"),
                            ("html", "HTML"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, help_text="HTML-formatted text"),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="module_pdfs/"),
                ),
                ("objectives", models.TextField(blank=True)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module Detail",
                "verbose_name_plural": "Module Details",
                "db_table": "module_details",
            },
        ),
        migrations.CreateModel(
            name="ModuleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="module_images/")),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Module Image",
                "verbose_name_plural": "Module Images",
                "db_table": "module_images",
                "ordering": ["module", "order"],
            },
        ),
        migrations.CreateModel(
            name="ModulePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module Package",
                "verbose_name_plural": "Module Packages",
                "db_table": "module_packages",
                "ordering": ["module", "order"],
            },
        ),
        migrations.CreateModel(
            name="ModuleToolOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ppt_generator", models.BooleanField(blank=True, null=True)),
                ("flashcard_creator", models.BooleanField(blank=True, null=True)),
                ("quiz_generator", models.BooleanField(blank=True, null=True)),
                ("lesson_plan_generator", models.BooleanField(blank=True, null=True)),
                ("worksheet_generator", models.BooleanField(blank=True, null=True)),
                ("mind_map_generator", models.BooleanField(blank=True, null=True)),
                ("simulation", models.BooleanField(blank=True, null=True)),
                ("practice_problems", models.BooleanField(blank=True, null=True)),
                ("step_by_step_solver", models.BooleanField(blank=True, null=True)),
                ("flashcard_student_visible", models.BooleanField(default=True)),
                ("quiz_student_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Module Tool Override",
                "verbose_name_plural": "Module Tool Overrides",
                "db_table": "module_tool_overrides",
            },
        ),
        migrations.CreateModel(
            name="PathModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("outcomes", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Path Module",
                "verbose_name_plural": "Path Modules",
                "db_table": "path_modules",
                "ordering": ["path", "order"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("pptx", "PowerPoint"),
                            ("docx", "Word Document"),
                            ("url", "External Link"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                ("url", models.URLField(blank=True, null=True, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "db_table": "resources",
                "ordering": ["module", "order"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "level",
                    models.CharField(
                        choices=[("SCHOOL", "School (K-12)"), ("UNIV", "University")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("ppt_generator", models.BooleanField(default=True)),
                ("flashcard_creator", models.BooleanField(default=True)),
                ("quiz_generator", models.BooleanField(default=True)),
                ("lesson_plan_generator", models.BooleanField(default=True)),
                ("worksheet_generator", models.BooleanField(default=True)),
                ("mind_map_generator", models.BooleanField(default=True)),
                ("simulation", models.BooleanField(default=False)),
                ("practice_problems", models.BooleanField(default=False)),
                ("step_by_step_solver", models.BooleanField(default=False)),
                ("ppt_generator_teacher_only", models.BooleanField(default=False)),
                ("flashcard_creator_teacher_only", models.BooleanField(default=False)),
                ("quiz_generator_teacher_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "db_table": "subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CoursePath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("course", "Course (All Students)"),
                            ("teacher", "Teacher's Prep"),
                            ("student", "Student (Personal)"),
                            ("offering", "Offering (Section Specific)"),
                        ],
                        db_index=True,
                        default="course",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g., Week 1: Introduction", max_length=255
                    ),
                ),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "objectives",
                    models.TextField(blank=True, help_text="Learning objectives"),
                ),
                (
                    "outcomes",
                    models.TextField(
                        blank=True, help_text="Learning outcomes mapped to CILOs"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("spec", "From Specification"),
                            ("book", "From Book"),
                            ("manual", "Manual Entry"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("not_generated", "Not Generated"),
                            ("partial", "Partial"),
                            ("complete", "Complete"),
                        ],
                        db_index=True,
                        default="not_generated",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="courses.course",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paths",
                        to="academics.courseoffering",
                    ),
                ),
                (
                    "source_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_paths",
                        to="content.book",
                    ),
                ),
                (
                    "source_toc_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.booktocitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Path",
                "verbose_name_plural": "Course Paths",
                "db_table": "course_paths",
                "ordering": ["course", "order"],
            },
        ),
    ]
