# Generated by Django 5.2.8 on 2025-11-20 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepath",
            name="student",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_paths",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coursepath",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_paths",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pathmodule",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.coursepath",
            ),
        ),
        migrations.AddField(
            model_name="moduletooloverride",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tool_override",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="modulepackage",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="moduleimage",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="moduledetail",
            name="module",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="courses.pathmodule",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["is_active"], name="subjects_is_acti_960049_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["level"], name="subjects_level_b9d30b_idx"),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="coursepath",
            index=models.Index(
                fields=["is_published"], name="course_path_is_publ_67d6a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursepath",
            index=models.Index(
                fields=["generation_status"], name="course_path_generat_637186_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursepath",
            index=models.Index(fields=["scope"], name="course_path_scope_2b9727_idx"),
        ),
        migrations.AddIndex(
            model_name="coursepath",
            index=models.Index(
                fields=["course", "scope"], name="course_path_course__e58e1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursepath",
            index=models.Index(
                fields=["teacher", "scope"], name="course_path_teacher_304c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursepath",
            index=models.Index(
                fields=["student", "scope"], name="course_path_student_9756ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursepath",
            index=models.Index(
                fields=["offering"], name="course_path_offerin_2bd9de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepath",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "course")),
                fields=("course", "scope"),
                name="unique_course_path_per_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepath",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "teacher")),
                fields=("course", "scope", "teacher"),
                name="unique_teacher_path_per_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepath",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "student")),
                fields=("course", "scope", "student"),
                name="unique_student_path_per_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursepath",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "offering")),
                fields=("offering", "scope"),
                name="unique_offering_path",
            ),
        ),
        migrations.AddIndex(
            model_name="pathmodule",
            index=models.Index(
                fields=["is_published"], name="path_module_is_publ_45a4f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathmodule",
            index=models.Index(
                fields=["category"], name="path_module_categor_a2375c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathmodule",
            constraint=models.UniqueConstraint(
                fields=("path", "slug"), name="unique_module_slug_per_path"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathmodule",
            constraint=models.UniqueConstraint(
                fields=("path", "title"), name="unique_module_title_per_path"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["type"], name="resources_type_f63025_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_required"], name="resources_is_requ_37d802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["url"], name="resources_url_4c4833_idx"),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                fields=("module", "type", "title"), name="unique_resource_per_module"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["is_active"], name="courses_is_acti_25e634_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["subject", "level"], name="courses_subject_5955a5_idx"
            ),
        ),
    ]
