# Generated by Django 5.2.8 on 2025-11-20 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("author", models.CharField(blank=True, max_length=255)),
                (
                    "isbn",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True, unique=True
                    ),
                ),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="books/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "books",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookAnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("text_extraction", "Text Extraction"),
                            ("ocr", "OCR Processing"),
                            ("cover_extraction", "Cover Image"),
                            ("toc_extraction", "TOC Extraction"),
                            ("full_processing", "Full Processing"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("progress_percent", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(blank=True, null=True)),
                ("processed_items", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Book Analysis Job",
                "verbose_name_plural": "Book Analysis Jobs",
                "db_table": "book_analysis_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("page_image", models.ImageField(upload_to="book_pages/")),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending OCR"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="0-1 confidence score", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ocr_completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Book Page",
                "verbose_name_plural": "Book Pages",
                "db_table": "book_pages",
                "ordering": ["book", "page_number"],
            },
        ),
        migrations.CreateModel(
            name="BookTOCItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Chapter"),
                            (2, "Section"),
                            (3, "Subsection"),
                            (4, "Sub-subsection"),
                            (5, "Sub-sub-subsection"),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("start_page", models.PositiveIntegerField()),
                ("end_page", models.PositiveIntegerField()),
                ("slug", models.SlugField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Book TOC Item",
                "verbose_name_plural": "Book TOC Items",
                "db_table": "book_toc_items",
                "ordering": ["book", "level", "order"],
            },
        ),
        migrations.CreateModel(
            name="ContentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("path", "Course Path"),
                            ("module", "Path Module"),
                            ("book", "Textbook"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("content_id", models.PositiveIntegerField(db_index=True)),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("comment", "View + Comment"),
                            ("edit", "Edit"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Content Access",
                "verbose_name_plural": "Content Access",
                "db_table": "content_access",
                "ordering": ["-granted_at"],
            },
        ),
    ]
