# Generated by Django 5.2.8 on 2025-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="textbooks", to="courses.course"
            ),
        ),
    ]
