# Generated by Django 5.2.8 on 2025-11-22 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bookanalysisjob",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_jobs",
                to="content.book",
            ),
        ),
        migrations.AddField(
            model_name="bookpage",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="content.book",
            ),
        ),
        migrations.AddField(
            model_name="booktocitem",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="toc_items",
                to="content.book",
            ),
        ),
        migrations.AddField(
            model_name="booktocitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="content.booktocitem",
            ),
        ),
        migrations.AddField(
            model_name="contentaccess",
            name="granted_by",
            field=models.ForeignKey(
                limit_choices_to={"role": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["status"], name="books_status_08b8fa_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["is_published"], name="books_is_publ_448494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["created_at"], name="books_created_a6d93f_idx"),
        ),
        migrations.AddIndex(
            model_name="bookanalysisjob",
            index=models.Index(
                fields=["book", "status"], name="book_analys_book_id_e4542d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookanalysisjob",
            index=models.Index(fields=["status"], name="book_analys_status_6b3eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="bookanalysisjob",
            index=models.Index(
                fields=["celery_task_id"], name="book_analys_celery__21820a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookpage",
            index=models.Index(
                fields=["book", "page_number"], name="book_pages_book_id_f7ba84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookpage",
            index=models.Index(
                fields=["ocr_status"], name="book_pages_ocr_sta_b582f5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookpage",
            unique_together={("book", "page_number")},
        ),
        migrations.AddIndex(
            model_name="booktocitem",
            index=models.Index(
                fields=["book", "parent"], name="book_toc_it_book_id_236ee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booktocitem",
            index=models.Index(
                fields=["book", "level"], name="book_toc_it_book_id_5a9e6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booktocitem",
            index=models.Index(
                fields=["start_page", "end_page"], name="book_toc_it_start_p_b8cdde_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booktocitem",
            unique_together={("book", "slug")},
        ),
        migrations.AddIndex(
            model_name="contentaccess",
            index=models.Index(
                fields=["user", "content_type"], name="content_acc_user_id_03d6da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentaccess",
            index=models.Index(
                fields=["expires_at"], name="content_acc_expires_7b1dca_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentaccess",
            unique_together={("user", "content_type", "content_id")},
        ),
    ]
