# Generated by Django 5.2.8 on 2025-11-22 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("assistant", "AI Assistant")],
                        db_index=True,
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tokens used by AI (for cost tracking)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="AI response time in milliseconds",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Auto-generated session title (from first message or AI)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(
                        default=0, help_text="Total messages in this session"
                    ),
                ),
                (
                    "total_time_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Total time spent in session (seconds)"
                    ),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of module content/progress when session started",
                        null=True,
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp of last message",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Chat Sessions",
                "db_table": "chat_sessions",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Notice title", max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Notice content (supports HTML/rich text)"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        help_text="Notice priority level",
                        max_length=20,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Published notices are visible to students",
                    ),
                ),
                (
                    "visible_to_all",
                    models.BooleanField(
                        default=True,
                        help_text="If False, only visible to specific students",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Pinned notices appear at the top",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Notice expires and hides after this date",
                        null=True,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Notices",
                "db_table": "notices",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
