# Generated by Django 5.2.8 on 2025-11-22 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="module",
            field=models.ForeignKey(
                help_text="Module this chat is about",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="courses.pathmodule",
            ),
        ),
    ]
