# Generated by Django 5.2.8 on 2025-11-22 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("communications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="student",
            field=models.ForeignKey(
                help_text="Student who owns this session",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="communications.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="course_offering",
            field=models.ForeignKey(
                help_text="Course offering this notice belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notices",
                to="academics.courseoffering",
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="created_by",
            field=models.ForeignKey(
                help_text="Teacher/admin who created this notice",
                limit_choices_to={"role__in": ["teacher", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_notices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="visible_to_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific students who can see this notice",
                limit_choices_to={"role": "student"},
                related_name="visible_notices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["student", "status"], name="chat_sessio_student_dda6d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["module", "status"], name="chat_sessio_module__cebdcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["last_message_at"], name="chat_sessio_last_me_f700c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["created_at"], name="chat_sessio_created_d061d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "timestamp"], name="chat_messag_session_4a3fea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["role"], name="chat_messag_role_ddd811_idx"),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["course_offering", "is_published"],
                name="notices_course__9aff03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(fields=["priority"], name="notices_priorit_e97978_idx"),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["is_pinned", "-created_at"], name="notices_is_pinn_2e83e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["expires_at"], name="notices_expires_566fb6_idx"
            ),
        ),
    ]
